### ISSUE TITLE
gem install gosu fails with "fatal error: AL/alut.h: No such file or directory"

### ISSUE THREAD

**Issue by madebydavid** [hybridgroup/kidsruby#130]
**What do you expect to happen?**
bundle install to work correctly when running the "If you also want Gosu" stuff in the README.md

**What actually happened?**
bundle install fails when building gosu with an error "fatal error: AL/alut.h: No such file or directory"

**What did you do to get this to happen?**
Checkout the kidsruby2 branch on a fresh ubuntu install, follow the steps in the "if you also want Gosu" section.
## System

OS: Linux precise32 3.2.0-23-generic-pae #36-Ubuntu
Version: kidsruby2

This was solved by running:
apt-get install m4 libalut-dev

Can you add these packages to the relevant section of the README.md?

**Comment by JeanLucMathay** [comment]
Try install libalut-dev:
sudo apt-get install libalut-dev
